#!/usr/bin/env python

import subprocess
import sys
import re

def is_exited(status):
    if len(status) == 0:
        return True

    if not 'Exited' in status:
        return False

    return re.search(r'(?:hours|days|weeks|months|years)', status)

proc = subprocess.Popen(["docker", "ps", "-a"], stdout=subprocess.PIPE)
stdout, stderr = proc.communicate()

if proc.returncode != 0:
    sys.exit(proc.returncode)

lines = str(stdout).rstrip().split('\n')
header = lines[0]
rows = lines[1:]
status_header = re.search(r"(STATUS\s+)", header)
status_start = status_header.start(1)
status_end = status_header.end(1)
remove_containers=[row.split()[0] for row in rows if is_exited(row[status_start:status_end].strip())]

if len(remove_containers) > 0:
    subprocess.check_call(["docker", "rm", "-v"] + remove_containers)
