#!/bin/bash

####################
#
# Delete containers that have exited, but were not successfully deleted
# when the jenkins job completed.
#
# Normally, the plugin will delete the container after the job completes.
# This is just a failsafe to prevent old containers from piling up.
#
####################

set -o nounset

docker ps -a | while read -r line; do
    container_id=$(echo "${line}" | cut -c 1-20)
    exited=$(echo "${line}" | cut -c 93-117)

    if [[ "${exited}" =~ days|weeks|months|years ]]; then
        echo Removing container ${container_id} that ${exited}
        docker rm ${container_id} >/dev/null
    fi
done
